local L = AceLibrary("AceLocale-2.2"):new("Baggins")

--[[ Ugly quite ASCII-safe translation table :)
   `a : \195\160    `e : \195\168    ^i : \195\174    ^o : \195\180   `u : \195\185
   'a : \195\161    'e : \195\169    ¨i : \195\175    ¨o : \195\182   ^u : \195\187
   ^a : \195\162    ^e : \195\170                     oe : \197\147   ¨u : \195\188
   ¨a : \195\164    ¨e : \195\171                               
   ae : \195\166
                                     
   ,c : \195\167                                    
--]]

L:RegisterTranslations("frFR", function()
	return {		
		--itemtypes, these must match the Type and SubType returns from GetItemInfo for the ItemType rule to work
		["Armor"] = "Armure",
			["Cloth"] = "Tissu",
			["Idols"] = "Idoles",
			["Leather"] = "Cuir",
			["Librams"] = "Librams",
			["Mail"] = "Mailles",
			["Miscellaneous"] = "Divers",
			["Shields"] = "Boucliers",
			["Totems"] = "Totems",
			["Plate"] = "Plaques",
		["Consumable"] = "Consommables",
		["Container"] = "Conteneur",
			["Bag"] = "Conteneur",
			["Enchanting Bag"] = "Sac d'enchanteur",
			["Engineering Bag"] = "Sac d'ing\195\169nieur",
			["Herb Bag"] = "Sac d'herbes",
			["Soul Bag"] = "Sac d'\195\162me",
		["Key"] = "Cl\195\169",
		["Miscellaneous"] = "Divers",
			["Junk"] = "Camelote",
		["Reagent"] = "Composant",
		["Recipe"] = "Recette",
			["Alchemy"] = "Alchimie",
			["Blacksmithing"] = "Forge",
      ["Book"] = "Livre",
			["Cooking"] = "Cuisine",
			["Enchanting"] = "Enchantement",
			["Engineering"] = "Ing\195\169nierie",
			["First Aid"] = "Secourisme",
			["Leatherworking"] = "Travail du cuir",
			["Tailoring"] = "Couture",
		["Projectile"] = "Projectile",
			["Arrow"] = "Fl\195\168che",
			["Bullet"] = "Balle",
		["Quest"] = "Qu\195\170te",
		["Quiver"] = "Carquois",
			["Ammo Pouch"] = "Giberne",
			["Quiver"] = "Carquois",
		["Trade Goods"] = "Artisanat",
			["Devices"] = "Appareils",
			["Explosives"] = "Explosifs",
			["Parts"] = "El\195\169ments",
--      ["Gems"] = "Gemmes",
		["Weapon"] = "Arme",
			["Bows"] = "Arcs",
			["Crossbows"] = "Arbal\195\168tes",
			["Daggers"] = "Dagues",
			["Guns"] = "Fusils",
			["Fishing Pole"] = "Canne \195\160 p\195\170che",
			["Fist Weapons"] = "Armes de pugilat",
			["Miscellaneous"] = "Divers",
			["One-Handed Axes"] = "Haches \195\160 une main",
			["One-Handed Maces"] = "Maces \195\160 une main",
			["One-Handed Swords"] = "Ep\195\169es \195\160 une main",
			["Polearms"] = "Armes d'hast",
			["Staves"] = "B\195\162tons",
			["Thrown"] = "Armes de jet",
			["Two-Handed Axes"] = "Haches \195\160 deux mains",
			["Two-Handed Maces"] = "Maces \195\160 deux mains",
			["Two-Handed Swords"] = "Ep\195\169es \195\160 deux mains",
			["Wands"] = "Baguettes",
--		--end of localizations needed for rules to work	
		
--		["Baggins"] = true,
		["Toggle All Bags"] = "Baculer tous les sacs",
		["Columns"] = "Colonnes",
		["Number of Columns shown in the bag frames"] = "Nombre de colonnes affich\195\169es dans les sacs",
		["Layout"] = "Disposition",
		["Layout of the bag frames."] = "Disposition des sacs",
		["Automatic"] = "Automatique",
		["Automatically arrange the bag frames as the default ui does"] = "Arrange automatiquement les sacs comme le fait Blizzard",
		["Manual"] = "Manuelle",
		["Each bag frame can be positioned manually."] = "Chaque sac peut \195\170tre positionn\195\169 manuellement.",
		["Show Section Title"] = "Afficher les titres de section",
		["Show a title on each section of the bags"] = "Affiche un titre pour chaque section des sacs",
		["Sort"] = "Tri",
		["How items are sorted"] = "M\195\169thode de tri des objets",
		["Quality"] = "Qualit\195\169",
		["Items are sorted by quality."] = "Les objets sont tri\195\169s par qualit\195\169",
		["Name"] = "Nom",
		["Items are sorted by name."] = "Les objets sont tri\195\169s par nom.",
		["Hide Empty Sections"] = "Cacher les sections vides",
		["Hide sections that have no items in them."] = "Cache les sections qui ne comportent aucun objet",
		["Hide Default Bank"] = "Cacher la banque originale",
		["Hide the default bank window."] = "Cache la fenêtre de banque originale.",
		["FuBar Text"] = "Texte FuBar",
		["Options for the text shown on fubar"] = "Options du texte affich\195\169 dans FuBar",
		["Show empty bag slots"] = "Afficher l'espace libre",
		["Show used bag slots"] = "Afficher l'espace utilis\195\169",
		["Show Total bag slots"] = "Afficher l'espace total",
		["Combine Counts"] = "Comptes combin\195\169s",
		["Show only one count with all the seclected types included"] = "N'affiche qu'un seul compte combinant tous les types indiqu\195\169s",
		["Show Ammo Bags Count"] = "Compter les munitions",
		["Show Soul Bags Count"] = "Compter les fragments d'\195\162me",
		["Show Specialty Bags Count"] = "Compter le contenu des sacs de profession",
		["Show Specialty (profession etc) Bags Count"] = "Compte le contenu des sacs de profession",
		["Set Layout Bounds"]= "D\195\169finir les limites de placements",
		["Shows a frame you can drag and size to set where the bags will be placed when Layout is automatic"] = 
			"Affiche un cadre mobile et redimensionnable pour indiquer o\195\185 les sacs seront plac\195\169s en mode automatique",
		["Lock"] = "Verrouiler les sacs",
		["Locks the bag frames making them unmovable"] = "Verrouiler les sacs qu'ils ne puissent plus \195\170tre d\195\169plac\195\169s",
		["Shrink Width"] = "R\195\169duire la largeur",
		["Shrink the bag's width to fit the items contained in them"] = "Adapte la largeur des sacs \195\160 leur contenu",
		["Compress"] = "Affichage compact",
		["Compress Multiple stacks into one item button"] = "Affiche toutes les piles d'un m\195\170me objet en un seul bouton",
		["Compress All"] = "Tout compacter",
		["Show all items as a single button with a count on it"] = "Regroupe tous les objets",
		["Compress Empty Slots"] = "Compacter les emplacements vides",
		["Show all empty slots as a single button with a count on it"] = "Regroupe les emplacements vides",
		["Compress Soul Shards"] = "Compacter les fragment d'\195\162mes",
		["Show all soul shards as a single button with a count on it"] = "Regroupe les fragments d'\195\162mes",
		["Compress Ammo"] = "Compacter les munitions",
		["Show all ammo as a single button with a count on it"] = "Regroupe les munitions",
		["Quality Colors"]= "Coloration par qualit\195\169",
		["Color item buttons based on the quality of the item"] = "Colore les boutons selon la qualit\195\169 des objets",
		["Enable"] = "Activer",
		["Enable quality coloring"] = "Activer la coloration par qualit\195\169",
		["Color Threshold"] = "Seuil de coloration",
		["Only color items of this quality or above"] = "Ne colore que les objets au-dessus de ce seuil",
		["Color Intensity"] = "Intensit\195\169 de coloration",
		["Intensity of the quality coloring"] = "Intensit\195\169 de la coloration par qualit\195\169",
		["Edit Bags"] = "Editer les sacs",
		["Edit the Bag Definitions"] = "Edite les d\195\169finitions des sacs",
		["Edit Categories"] = "Editer les cat\195\169gories",
		["Edit the Category Definitions"] = "Edite les d\195\169finitions des cat\195\169gories",
		["Load Profile"] = "Charger un profil",
		["Load a built-in profile: NOTE: ALL Custom Bags will be lost and any edited built in categories will be lost."] = 
			"Charge un profil pr\195\169d\195\169fini. NOTE: TOUS les sacs personnalis\195\169s et cat\195\169gories modifi\195\169es seront perdus.",
		["Default"] = "D\195\169faut",
		["A default set of bags sorting your inventory into categories"] = "Un ensemble de sacs par d\195\169faut, triant votre inventaire en cat\195\169gories",
		["All in one"] = "Tout en un",
		["A single bag containing your whole inventory, sorted by quality"] = "Un seul contenant tout l'inventaire, tri\195\169 par qualit\195\169",
		["Scale"] = "Echelle",
		["Scale of the bag frames"] = "Echelle d'affichage des sacs",
--		--bagtypes
		["Backpack"] = "Sac \195\160 dos",
		["Bag1"] = "Sac n\194\1761",
		["Bag2"] = "Sac n\194\1762",
		["Bag3"] = "Sac n\194\1763",
		["Bag4"] = "Sac n\194\1764",
		["Bank Frame"] = "Contenu de la banque",
		["Bank Bag1"] = "Sac de banque n\194\1761",
		["Bank Bag2"] = "Sac de banque n\194\1762",
		["Bank Bag3"] = "Sac de banque n\194\1763",
		["Bank Bag4"] = "Sac de banque n\194\1764",
		["Bank Bag5"] = "Sac de banque n\194\1765",
		["Bank Bag6"] = "Sac de banque n\194\1766",
		["Bank Bag7"] = "Sac de banque n\194\1767",
		["KeyRing"] = "Trouseau de cl\195\169s",
		
		--qualoty names
		["Poor"] = "Mauvais",
		["Common"] = "Commun",
		["Uncommon"] = "Inhabituel",
		["Rare"] = "Rare",
		["Epic"] = "Epique",
		["Legendary"] = "L\195\169gendaire",
		["Artifact"] = "Artefact",
		
		["None"] = "Aucun",
		["All"] = "Tous",
		
		["Item Type"] = "Type d'objet",
		["Filter by Item type and sub-type as returned by GetItemInfo"] = "Filtre sur le type et sous-type d'objets",
		["ItemType - "] = "Type d'objet - ",
		["Item Type Options"] = "Choix de types d'objet",
		["Item Subtype"] = "Sous-type d'objet",

		["Container Type"] = "Type de sac",
		["Filter by the type of container the item is in."] = "Filtre sur le type de contenant",
		["Container : "] = "Sac",
		["Container Type Options"] = "Choix de types de sacs",

		["Item ID"] = "Identifiants d'objets",
		["Filter by ItemID, this can be a space delimited list or ids to match."] = 
			"Filter par identifiant d'objets; cela peut-\195\170tre une liste d'identifiants s\195\169par\195\169s par des espaces",
		["ItemIDs "] = "Identifiants ",
		["ItemID Options"] = "Choix d'identifiants",
		["Item IDs (space seperated list)"] = "Indentifiants, s\195\169par\195\169s par des espaces",
		
		["Bag "] = "Sac ",
		["Filter by the bag the item is in"] = "Filtre sur le sac contenant les objets",
		["Bag Options"] = "Choix de sacs",
		["Ignore Empty Slots"] = "Ignorer les emplacements vides",
		
		["Item Name"] = "Nom d'objet",
		["Filter by Name or partial name"] = "Filtre sur nom ou partie du nom",
		["Name: "] = "Nom: ",
		["Item Name Options"] = "Choix du nom",
		["String to Match"] = "Cha\195\174ne \195\160 rechercher",
		
		["PeriodicTable Set"] = "Ensemble PeriodicTable",
		["Filter by PeriodicTable Set"] = "Filtre sur un ensemble 'PeriodicTable'",
		["Periodic Table Set Options"] = "Choix d'ensembles PeriodicTable",
		["Set"] = "Ensembe",
		
		["Empty Slots"] = "Espace vide",
		["Empty bag slots"] = "Emplacements de sac vides",
		
		["Ammo Bag"] = "Sac de munitions",
		["Items in an ammo pouch or quiver"] = "Objets dans un sac de munition",
		["Ammo Bag Slots"] = "Emplacements de sac de munition",
		
		["Quality"] = "Qualit\195\169",
		["Filter by Item Quality"] = "Filtre sur la qualit\195\169",
		["Quality Options"] = "Choix de qualit\195\169s",
		["Comparison"] = "Comparaison",
		
		["Location"] = "Place d'\195\169quipement",
		["Filter by Equip Location as returned by GetItemInfo"] = 
			"Filtre sur l'emplacement qu'occupera l'objet sur votre personnage",
		["Equip Location"] = "Place d'\195\169quipement",
		["Equip Location Options"] = "Choix de places d'\195\169quipement",
		
		["Unfiltered Items"] = "Objets non-filtr\195\169s",
		["Matches all items that arent matched by any other bag, NOTE: this should be the only rule in a category, others will be ignored"] = 
			"Regroupe tous les items qui ne vont pas ailleurs. NOTE: cela doit \195\170tre la seule r\195\168gle de la cat\195\169gorie, les autres seront ignor\195\169es",
		["Unfiltered"] = "Non-filtr\195\169",
		
		["Bind"] = "Lien",
		["Filter based on if the item binds, or if it is already bound"] = 
			"Filtre sur la fa\195\167on dont un objet est li\195\169 (ou pas)",
		["Bind *unset*"] = "Lien ind\195\169fini",
		["Unbound"] = "Non-li\195\169",
		["Bind Options"] = "Choix de type de liens",
		["Bind Type"] = "Type de lien",
		-- Globalstring ["Binds on pickup"] = "Li\195\169 quand ramass\195\169",
		-- Globalstring ["Binds on equip"] = "Li\195\169 quand \195\169quip\195\169",
		-- Globalstring ["Binds on use"] = "Li\195\169 quand utilis\195\169",
		
		["ItemID: "] = "Identifiant d'objet: ",
		["Item Type: "] = "Type d'objet: ",
		["Item Subtype: "] = "Sous-type d'objet: ",
		
		["Click a bag to toggle it. Shift-click to move it up. Alt-click to move it down"] = 
			"Cliquer sur un sac pour l'afficher/cacher. Shift+clic pour le remonter. Alt+clic pour le descendre.",
		
		["Bags"] = "Sacs",
		["Options"] = "Options",
		["Open With All"] = "Ouvrir avec tous",
		["Bank"] = "Banque",
		["Sections"] = "Sections",
		["Categories"] = "Cat\195\169gories",
		["Add Category"] = "Ajouter une cat\195\169gorie",
		["New Section"] = "Nouvelle section",
		["New Bag"] = "Nouveau sac",
		["Close"] = "Fermer",
		["Click on an entry to open. Shift-Click to move up. Alt-Click to move down. Ctrl-Click to delete."] = 
			"Cliquer sur une entr\195\169e pour l'ouvrir. Shift+clic pour monter. Alt+clic pour descendre. Ctrl+clic pour supprimer.",
		["Rules"] = "R\195\168gles",
		["New Rule"] = "Nouvelle r\195\168gle",
		["Add Rule"] = "Ajouter une r\195\168gle",
		["New Category"] = "Nouvelle cat\195\169gorie",
		["Apply"] = "Appliquer",
		["Click on an entry to open. Ctrl-Click to delete."] = "Cliquer sur une entr\195\169e pour l'ouvrir. Ctrl+clic pour supprimer.",
		
		["Editing Rule"] = "Edition de r\195\168gle",
		["Type"] = "Type",
		["Select a rule type to create the rule"] = "S\195\169lectionnez un type de r\195\168gle ou cr\195\169er une r\195\168gle",
		["Operation"] = "Operation",
		["AND"] = "ET",
		["OR"] = "OU",
		["NOT"] = "NON",
		
		["Baggins - New Bag"] = "Baggins - nouveau sac",
		["Baggins - New Section"] = "Baggins - nouvelle section",
		["Baggins - New Category"] = "Baggins - nouvelle cat\195\169gorie",
		["Accept"] = "Accepter",
		["Cancel"] = "Annuler",
		
		["Are you sure you want to delete this Bag? this cannot be undone"] = 
			"Etes-vous s\195\187r de vouloir supprimer ce sac ? Il est impossible d'annuler",
		["Are you sure you want to delete this Section? this cannot be undone"] = 
			"Etes-vous s\195\187r de vouloir supprimer cette section ? Il est impossible d'annuler",
		["Are you sure you want to remove this Category? this cannot be undone"] =
			"Etes-vous s\195\187r de vouloir supprimer cette cat\195\169gorie ? Il est impossible d'annuler",
		["Are you sure you want to remove this Rule? this cannot be undone"] =
			"Etes-vous s\195\187r de vouloir supprimer cette r\195\168gle ? Il est impossible d'annuler",
		["Delete"] = "Supprimer",
--		["Cancel"] = true, -- Duplciate
		
		["That category is in use by one or more bags, you cannot delete it."] = 
			"Cette cat\195\169gorie est utilis\195\169 par un ou plusieurs sacs, vous ne pouvez pas la supprimer",
		["A category with that name already exists."] = 
			"Une cat\195\169gorie avec ce nom existe d\195\169j\195\160",
		
		["Drag to Move\nRight-Click to Close"] = "Tirer pour d\195\169placer\nClic droit pour fermer",
		["Drag to Size"] = "Tirer pour dimensionner",
		
		["Previous "] = "Pr\195\169cedent ",
		["Next "] = "Suivant ",
		
--		["All In One"] = true, -- Duplicate
		["Bank All In One"] = "Banque tout-en-un",
		["Bank Bags"] = "Sacs de banque",
		
		["Equipment"] = "Equipement",
		["Weapons"] = "Armes",
		["Quest Items"] = "Objets de qu\195\170te",
		["Consumables"] = "Consommables",
		["Water"] = "Boisson",
		["Food"] = "Nourriture",
		["FirstAid"] = "Secourisme",
		["Potions"] = "Potions",
		["Scrolls"] = "Parchemins",
		["Misc"] = "Divers",
		["Misc Consumables"] = "Consommables divers",

		["Mats"] = "Mat\195\169riaux",
		["Tradeskill Mats"] = "Mat\195\169riaux d'artisanat",
		["Gathered"] = "R\195\169colte",
		["BankBags"] = "Sacs de banque",
		["Ammo"] = "Munition",
		["AmmoBag"] = "Sac de munition",
		["SoulShards"] = "Fragments d'\195\162mes",
		["SoulBag"] = "Sac de Fragments d'\195\162mes",
		["Other"] = "Autre",
		["Trash"] = "Camelote",
		["TrashEquip"] = "Camelote - \195\169quipement",
		["Empty"] = "Vide",
		["Bank Equipment"] = "Banque - \195\169quipement",
		["Bank Quest"] = "Banque - objets de qu\195\170te",
		["Bank Consumables"] = "Banque - consommables",
		["Bank Trade Goods"] = "Banque - Artisanat",
		["Bank Other"] = "Banque - divers",
		
		["Highlight New Items"] = "Indiquer les nouveaux objets",
		["Add *New* to new items, *+++* to items that you have gained more of."] = 
			"Ajoute *N* sur les nouveaux objets et *+++* sur ceux dont vous avez gagn\195\169 de nouveaux exemplaires.",
		["Reset New Items"] = "R\195\160Z noveaux objets",
		["Resets the new items highlights."] = "Remets \195\160 z\195\169ro les indicateurs de nouveaux objets.",
		["*New*"] = "*N*",

		["Add To Category"] = "Ajouter \195\160 une cat\195\169gorie",
		["Exclude From Category"] = "Exclure d'une cat\195\169gorie",
		["Item Info"] = "Informations",
		["Quality: "] = "Qualit\195\169: ",
		["Level: "] = "Niveau: ",
		["MinLevel: "] = "Niveau requis: ",
		["Stack Size: "] = "Taille de pile: ",
		["Equip Location: "] = "",
		["Periodic Table Sets"] = "",
		
		["Hide Duplicate Items"] = "Cacher les doublons",
		["Prevents items from appearing in more than one section/bag."] = 
			"Evite d'afficher les m\195\170mes objets dans plus d'un(e) section/sac.",
			
		["Optimize Section Layout"] = "Optimiser la disposition des sections",
		["Change order and layout of sections in order to save display space."] = 
			"Change l'ordre et la disposition des sections pour \195\169conomiser l'espace d'affichage",
		
	}
end)