local L = AceLibrary("AceLocale-2.2"):new("Baggins")

L:RegisterTranslations("koKR", function()
	return {
		--itemtypes, these must match the Type and SubType returns from GetItemInfo for the ItemType rule to work
		["Armor"] = "방어구",
			["Cloth"] = "천", 
			["Idols"] = "우상", 
			["Leather"] = "가죽", 
			["Librams"] = "성서", 
			["Mail"] = "사슬", 
			["Miscellaneous"] = "기타", 
			["Shields"] = "방패", 
			["Totems"] = "토템", 
			["Plate"] = "판금", 
		["Consumable"] = "소비 용품",  
		["Container"] = "가방",
			["Bag"] = "가방",  
			["Enchanting Bag"] = "마법부여 가방",  
			["Engineering Bag"] = "기계공학 가방",  
			["Herb Bag"] = "약초 가방",  
			["Soul Bag"] = "영혼의 가방",  
		["Key"] = "열쇠",  
		["Miscellaneous"] = "기타",
			["Junk"] = "잡동사니",  
		["Reagent"] = "재료",  
		["Recipe"] = "제조법",
			["Alchemy"] = "연금술", 
			["Blacksmithing"] = "대장기술", 
			["Book"] = "책", 
			["Cooking"] = "요리", 
			["Enchanting"] = "마법부여", 
			["Engineering"] = "기계공학", 
			["First Aid"] = "응급치료", 
			["Leatherworking"] = "가죽세공", 
			["Tailoring"] = "재봉술", 
		["Projectile"] = "투사체",
			["Arrow"] = "화살",  
			["Bullet"] = "탄환", 
		["Quest"] = "퀘스트", 
		["Quiver"] = "화살통", 
			["Ammo Pouch"] = "탄약 주머니", 
			["Quiver"] = "화살통", 
		["Trade Goods"] = "직업 용품", 
			["Devices"] = "장치", 
			["Explosives"] = "폭발물", 
			["Parts"] = "부품", 
			["Gems"] = "보석",
		["Weapon"] = "무기",
			["Bows"] = "활류", 
			["Crossbows"] = "석궁류", 
			["Daggers"] = "단검류", 
			["Guns"] = "총기류", 
			["Fishing Pole"] = "낚싯대", 
			["Fist Weapons"] = "장착 무기류", 
			["Miscellaneous"] = "기타",
			["One-Handed Axes"] = "한손 도끼류", 
			["One-Handed Maces"] = "한손 둔기류", 
			["One-Handed Swords"] = "한손 도검류", 
			["Polearms"] = "장창류", 
			["Staves"] = "지팡이류", 
			["Thrown"] = "투척 무기류", 
			["Two-Handed Axes"] = "양손 도끼류", 
			["Two-Handed Maces"] = "양손 둔기류", 
			["Two-Handed Swords"] = "양손 도검류", 
			["Wands"] = "마법봉류", 
		--end of localizations needed for rules to work	
		
	
--		["Baggins"] = true,
		["Toggle All Bags"] = "모든 가방 열기/닫기",
		["Columns"] = "칸",
		["Number of Columns shown in the bag frames"] = "가방창의 칸수를 조절합니다",
		["Layout"] = "레이아웃",
		["Layout of the bag frames."] = "가방창의 레이아웃을 설정합니다",
		["Automatic"] = "자동",
		["Automatically arrange the bag frames as the default ui does"] = "가방창을 기본 UI로 자동으로 배열합니다",
		["Manual"] = "수동",
		["Each bag frame can be positioned manually."] = "각각의 가방창을 수동으로 배열합니다.",
		["Show Section Title"] = "분류명 표시",
		["Show a title on each section of the bags"] = "각각의 가방의 분류명칭을 표시합니다.",
		["Sort"] = "정렬",
		["How items are sorted"] = "아이템을 어떻게 정렬할지를 선택합니다",
		["Quality"] = "품질",
		["Items are sorted by quality."] = "아이템을 품질에 따라서 분류합니다.",
		["Name"] = "이름",
		["Items are sorted by name."] = "아이템을 이름에 따라서 분류합니다.",
		["Hide Empty Sections"] = "빈 분류 숨기기",
		["Hide sections that have no items in them."] = "해당 분류의 아이템이 없는 경우 해당 분류를 숨깁니다.",
		["Hide Default Bank"] = "기본 은행 숨김",
		["Hide the default bank window."] = "기본 은행창을 숨깁니다",
		["FuBar Text"] = "텍스트 표시",
		["Options for the text shown on fubar"] = "페널에 플러그인 텍스트를 표시합니다.",
		["Show empty bag slots"] = "빈 가방 슬롯 표시",
		["Show used bag slots"] = "사용중인 가방 슬롯 표시",
		["Show Total bag slots"] = "총 가방 슬롯 표시",
		["Combine Counts"] = "갯수 통합",
		["Show only one count with all the seclected types included"] = "선택된 형식에 포함되어 있는 아이템의 갯수를 합쳐서 표시합니다",
		["Show Ammo Bags Count"] = "투사체 가방 갯수 표시",
		["Show Soul Bags Count"] = "영혼의 가방 갯수 표시",
		["Show Specialty Bags Count"] = "특수 가방 갯수 표시",
		["Show Specialty (profession etc) Bags Count"] = "특수(전문기술 등) 가방 갯수 표시",
		["Set Layout Bounds"]= "레이아웃 기반 설정",
		["Shows a frame you can drag and size to set where the bags will be placed when Layout is automatic"] = "레이아웃을 자동으로 정렬하는 드래그하고 크기를 조절이 가능한 창을 설정합니다",
		["Lock"] = "잠금",
		["Locks the bag frames making them unmovable"] = "가방창의 위치를 고정합니다",
		["Shrink Width"] = "너비 자동 조절",
		["Shrink the bag's width to fit the items contained in them"] = "창의 크기를 아이템의 갯수에 따라서 자동으로 조절합니다",
		["Compress"] = "합침",
		["Compress Multiple stacks into one item button"] = "아이템을 합쳐서 하나의 버튼에 표시합니다",
		["Compress All"] = "모두 합침",
		["Show all items as a single button with a count on it"] = "합칠 수 있는 모든 아이템을 합쳐서 하나의 버튼에 갯수만을 표시하도록 합니다",
		["Compress Empty Slots"] = "빈 슬롯 합침",
		["Show all empty slots as a single button with a count on it"] = "가방 안의 빈 슬롯을 합쳐서 하나의 버튼에 갯수만을 표시합니다",
		["Compress Soul Shards"] = "영혼의 조각 합침",
		["Show all soul shards as a single button with a count on it"] = "가방 안의 영혼의 조각을 합쳐서 하나의 버튼에 갯수만을 표시합니다",
		["Compress Ammo"] = "투사체 합침",
		["Show all ammo as a single button with a count on it"] = "가방 안의 투사체를 합쳐서 하나의 버튼에 갯수만을 표시합니다",
		["Quality Colors"]= "품질 색상",
		["Color item buttons based on the quality of the item"] = "아이템의 품질에 따라서 아이템의 버튼 색상을 변경합니다",
		["Enable"] = "사용",
		["Enable quality coloring"] = "품질 색상 기능 사용",
		["Color Threshold"] = "색상 한계선",
		["Only color items of this quality or above"] = "해당 품질 이상의 아이템에만 품질 색상 기능을 사용합니다",
		["Color Intensity"] = "색상 농도",
		["Intensity of the quality coloring"] = "품질 색상의 농도를 설정합니다",
		["Edit Bags"] = "가방 편집",
		["Edit the Bag Definitions"] = "가방별 정의를 편집합니다.",
		["Edit Categories"] = "분류 편집",
		["Edit the Category Definitions"] = "분류별 정의를 편집합니다.",
		["Load Profile"] = "프로파일 불러오기",
		["Load a built-in profile: NOTE: ALL Custom Bags will be lost and any edited built in categories will be lost."] = "기본 설정된 프로파일을 불러옵니다. 주의: 모든 사용사 설정이 사라집니다.",
		["Default"] = "기본값",
		["A default set of bags sorting your inventory into categories"] = "분류별로 인벤토리를 정렬하는 설정입니다",
		["All in one"] = "통합 가방",
		["A single bag containing your whole inventory, sorted by quality"] = "모든 아이템을 하나의 통합가방에 품질별로 정렬하는설정입니다",
		["Scale"] = "크기",
		["Scale of the bag frames"] = "가방창의 크기를 조절합니다",
		--bagtypes
		["Backpack"] = "소지품",
		["Bag1"] = "1번 가방",
		["Bag2"] = "2번 가방",
		["Bag3"] = "3번 가방",
		["Bag4"] = "4번 가방",
		["Bank Frame"] = "은행창",
		["Bank Bag1"] = "1번 은행 가방",
		["Bank Bag2"] = "2번 은행 가방",
		["Bank Bag3"] = "3번 은행 가방",
		["Bank Bag4"] = "4번 은행 가방",
		["Bank Bag5"] = "5번 은행 가방",
		["Bank Bag6"] = "6번 은행 가방",
		["Bank Bag7"] = "7번 은행 가방",
		["KeyRing"] = "열쇠 고리",
		
		--qualoty names
		["Poor"] = "하급",
		["Common"] = "일반",
		["Uncommon"] = "고급",
		["Rare"] = "희귀",
		["Epic"] = "영웅",
		["Legendary"] = "전설",
		["Artifact"] = "유물",
		
		["None"] = "없음",
		["All"] = "통합 가방",
		
		["Item Type"] = "아이템 종류",
		["Filter by Item type and sub-type as returned by GetItemInfo"] = "GetItemInfo 함수값인 아이템 종류와 세부 종류에 따라서 분류합니다",
		["ItemType - "] = "아이템 종류 - ",
		["Item Type Options"] = "아이템 종류 설정",
		["Item Subtype"] = "아이템 세부 종류",

		["Container Type"] = "가방 종류",
		["Filter by the type of container the item is in."] = "아이템이 들어 있는 가방의 종류에 따라서 분류합니다",	
		["Container : "] = "가방 : ",
		["Container Type Options"] = "가방 종류 설정",

		["Item ID"] = "아이템ID",
		["Filter by ItemID, this can be a space delimited list or ids to match."] = "아이템ID별로 아이템을 분류합니다.",
		["ItemIDs "] = "아이템ID",
		["ItemID Options"] = "아이템ID 설정",
		["Item IDs (space seperated list)"] = "아이템ID(공백으로 복구 입력)"		,
		["New"] = "신규",
		["Current IDs, click to remove"] = "현재 ID, 클릭시 제거",
		
		["Filter by the bag the item is in"] = "아이템이 들어 있는 가방에 따라서 분류합니다",
		["Bag "] = "가방 ",
		["Bag Options"] = "가방 설정",
		["Ignore Empty Slots"] = "공란 무시",
		
		["Item Name"] = "아이템 이름",
		["Filter by Name or partial name"] = "아이템의 이름 또는 이름의 일부분으로 분류합니다",
		["Name: "] = "이름: ",
		["Item Name Options"] = "아이템 이름 설정",
		["String to Match"] = "일치할 문자열",
		
		["PeriodicTable Set"] = "PeriodicTable 세트",
		["Filter by PeriodicTable Set"] = "PeriodicTable 세트별로 분류합니다",
		["Periodic Table Set Options"] = "Periodic Table 세트 설정",
		["Set"] = "세트",
		
		["Empty Slots"] = "공란",
		["Empty bag slots"] = "가방 공란",
		
		["Ammo Bag"] = "투사체 가방",
		["Items in an ammo pouch or quiver"] = "화살통 또는 탄약 주머니 안의 아이템",
		["Ammo Bag Slots"] = "투사체 가방 슬롯",
		
		["Quality"] = "품질",
		["Filter by Item Quality"] = "아이템 품질별로 분류합니다",
		["Quality Options"] = "품질 설정",
		["Comparison"] = "비교",
		
		["Equip Location"] = "착용 부위",
		["Filter by Equip Location as returned by GetItemInfo"] = "GetItemInfo 함수값인 착용부위별로 분류합니다",
		["Equip Location Options"] = "착용 부위 설정",
		["Location"] = "위치",
		
		["Unfiltered Items"] = "미분류 아이템",
		["Matches all items that arent matched by any other bag, NOTE: this should be the only rule in a category, others will be ignored"] = "다른 가방에 속하지 않는 모든 아이템, 주의: 이것은 분류 규칙만 적용됩니다. 기타의 사항은 무시합니다",
		["Unfiltered"] = "미분류",
		
		["Bind"] = "귀속",
		["Filter based on if the item binds, or if it is already bound"] = "아이템의 귀속 시기별로 분류합니다",
		["Bind *unset*"] = "귀속 설정 없음",
		["Unbound"] = "귀속안됨",
		["Bind Options"] = "귀속 설정",
		["Bind Type"] = "귀속 방식",
		["Binds on pickup"] = "획득 시 귀속",
		["Binds on equip"] = "착용 시 귀속",
		["Binds on use"] = "사용 시 귀속",
		["Soulbound"] = "귀속 아이템",

		["Tooltip"] = "툴팁",
		["Filter based on text contained in its tooltip"] = "툴팁의 문구를 기본으로 필터링합니다",
		["Tooltip Options"] = "툴팁 설정",
		
		["ItemID: "] = "아이템ID: ",
		["Item Type: "] = "아이템 종류: ",
		["Item Subtype: "] = "아이템 세부 종류: ",
		
		["Click a bag to toggle it. Shift-click to move it up. Alt-click to move it down"] = "클릭시 가방을 토글, Shift-클릭시 위로, Alt-클릭시 아래로",
		
		["Bags"] = "가방",
		["Options"] = "설정",
		["Open With All"] = "모두 열기 시에 열기",
		["Bank"] = "은행",
		["Sections"] = "구분",
		["Categories"] = "분류",
		["Add Category"] = "분류 추가",
		["New Section"] = "신규 구분 추가",
		["New Bag"] = "신규 가방 추가",
		["Close"] = "닫기",
		["Click on an entry to open. Shift-Click to move up. Alt-Click to move down. Ctrl-Click to delete."] = "클릭시 전체 열기, Shift-클릭시 위로, Alt-클릭시 아래로, Ctrl 클릭시 삭제",
		["Rules"] = "규칙",
		["New Rule"] = "신규 규칙",
		["Add Rule"] = "규칙 추가",
		["New Category"] = "신규 분류 추가",
		["Apply"] = "적용",
		["Click on an entry to open. Ctrl-Click to delete."] = "클릭시 전체 열기, Ctrl-클릭시 삭제",
		
		["Editing Rule"] = "규칙 편집",
		["Type"] = "형식",
		["Select a rule type to create the rule"] = "규칙 작성의 형식을 선택합니다",
		["Operation"] = "인식자",
		["AND"] = "그리고",
		["OR"] = "또는",
		["NOT"] = "반면",
		
		["Baggins - New Bag"] = "Baggins - 신규 가방",
		["Baggins - New Section"] = "Baggins - 신규 구분",
		["Baggins - New Category"] = "Baggins - 신규 분류",
		["Accept"] = "수락",
		["Cancel"] = "취소",
		
		["Are you sure you want to delete this Bag? this cannot be undone"] = "정말로 이 가방을 삭제하시겠습니까? 복구가 불가능합니다",
		["Are you sure you want to delete this Section? this cannot be undone"] = "정말로 이 구분을 삭제하시겠습니까? 복구가 불가능합니다",
		["Are you sure you want to remove this Category? this cannot be undone"] = "정말로 이 분류를 제거하시겠습니까? 복구가 불가능합니다",
		["Are you sure you want to remove this Rule? this cannot be undone"] = "정말로 이 규칙을 제거하시겠습니까? 복구가 불가능합니다",
		["Delete"] = "삭제",
		["Cancel"] = "취소",
		
		["That category is in use by one or more bags, you cannot delete it."] = "이 분류는 한 개 이상의 가방에서 사용중입니다. 제거가 불가능 합니다",
		["A category with that name already exists."] = "해당 분류명은 이미 사용중입니다.",
		
		["Drag to Move\nRight-Click to Close"] = "드래그로 이동 우클릭으로 닫기",
		["Drag to Size"] = "드래그로 크기 조절",
		
		["Previous "] = "이전",
		["Next "] = "다음",
		
		["All In One"] = "통합 가방",
		["Bank All In One"] = "은행 통합 가방",
		["Bank Bags"] = "은행 가방",

		["Equipment"] = "착용 아이템",
		["Weapons"] = "무기",
		["Quest Items"] = "퀘스트 아이템",
		["Consumables"] = "소비 용품",
		["Water"] = "음료",
		["Food"] = "음식",
		["FirstAid"] = "응급치료",
		["Potions"] = "물약",
		["Scrolls"] = "두루마리",
		["Misc"] = "기타",
		["Misc Consumables"] = "기타 소비 용품",

		["Mats"] = "재료",
		["Tradeskill Mats"] = "전문기술 재료",
		["Gathered"] = "채집물",
		["BankBags"] = "은행가방",
		["Ammo"] = "투사체",
		["AmmoBag"] = "화살통",
		["SoulShards"] = "영혼의 조각",
		["SoulBag"] = "영혼의 가방",
		["Other"] = "기타",
		["Trash"] = "쓰레기",
		["TrashEquip"] = "쓰레기 아이템",
		["Empty"] = "공란",
		["Bank Equipment"] = "은행 착용장비",
		["Bank Quest"] = "은행 퀘스트아이템",
		["Bank Consumables"] = "은행 소비용품",
		["Bank Trade Goods"] = "은행 전문기술용품",
		["Bank Other"] = "은행 기타품목",
		
		["Add To Category"] = "분류 추가",
		["Exclude From Category"] = "분류에서 제거",
		["Item Info"] = "아이템 정보",
		["Quality: "] = "품질: ",
		["Level: "] = "레벨: ",
		["MinLevel: "] = "최저 레벨: ",
		["Stack Size: "] = "묶음 크기: ",
		["Equip Location: "] = "착용 부위: ",
--		["Periodic Table Sets"] = true,
		
		["Highlight New Items"] = "신규 아이템 강조",
		["Add *New* to new items, *+++* to items that you have gained more of."] = "신규 아이템에 *New*를, 추가 획득 아이템에 *+++*를 표시합니다.",
		["Reset New Items"] = "신규 아이템 초기화",
		["Resets the new items highlights."] = "신규 아이템 강조 기능을 초기화 합니다",
--		["*New*"] = true,
		
		["Hide Duplicate Items"] = "중복 아이템 숨김",
		["Prevents items from appearing in more than one section/bag."] = "아이템이 한 개 이상 표시되지 않습니다",
		
		["Optimize Section Layout"] = "구분 배열 최적화",
		["Change order and layout of sections in order to save display space."] = "저장된 표시 공간의 순서에 따라서 구분의 배열 순서를 변경합니다.",
		
		["All In One Sorted"]= "통합 가방 정렬",
		["A single bag containing your whole inventory, sorted into categories"]= "통합 가방 형태에서 분류별로 정렬합니다",
		
		["Compress Stackable Items"]= "묶음 아이템 합침",
		["Show stackable items as a single button with a count on it"]= "겹치는 아이템은 하나의 버튼으로 수량만을 표시합니다",

		["Appearance and layout"]= "외양과 배치",
		["Bags"]= "가방",
		["Bag display and layout settings"]= "가방 표시와 배치 설정",
		["Layout Type"]= "배치 형식",
		["Sets how all bags are laid out on screen."]= "화면상에 모든 가방의 배열을 설정합니다",
		["Shrink bag title"]= "가방 이름 너비",
		["Mangle bag title to fit to content width"]= "가방의 너비를 가방의 이름에 따라 조절합니다",
		["Sections"]= "구분",
		["Bag sections display and layout settings."]= "가방 안의 구분 간의 배열을 설정합니다",
		["Items"]= "아이템",
		["Item display settings"]= "아이템 표시 설정",
		["Bag Skin"]= "가방 스킨",
		["Select bag skin"]= "가방의 스킨을 선택합니다",
	}
end)